"""empty message

Revision ID: 5e2f882ba60d
Revises: 
Create Date: 2020-03-30 13:57:19.945343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2f882ba60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('follower_fname', sa.String(length=20), nullable=False),
    sa.Column('follower_lname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('follower_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_followers')
    # ### end Alembic commands ###
